setup:
    # Uncomment the following lines if you are using Ubuntu or Linux Mint
    # to confirm whether you have these packages are installed or not, run the following commands
    # sudo apt-get update
    # sudo apt-get install -y mysql-server mysql-client 
    # sudo install -y libmysqlclient-dev python3-dev python3-pip 
    # sudo apt-get install python3-venv -y
    pip install virtualenv
    source venv/bin/activate
    pip install -r requirements.txt
    # pip install Flask
    # pip install flask-sqlalchemy
    chmod u+x run.py    # make run.py executable
run:
    ./run.py
    # python3 run.py
