setup:
    pip install virtualenv
    source venv/bin/activate
    pip install -r requirements.txt
    # pip install Flask
    # pip install flask-sqlalchemy
    chmod u+x run.py
run:
    ./run.py
    # python3 run.py
